# Generated by Django 5.2 on 2025-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('RequestDate', models.DateTimeField(blank=True, null=True)),
                ('Company', models.TextField(blank=True, null=True)),
                ('Author', models.TextField(blank=True, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Worker', models.TextField(blank=True, null=True)),
                ('StartDate', models.DateTimeField(blank=True, null=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('IsReassigned', models.CharField(blank=True, max_length=5, null=True)),
                ('Confirmation', models.CharField(blank=True, max_length=5, null=True)),
                ('GroupId', models.BigIntegerField(blank=True, null=True)),
                ('MessageId', models.BigIntegerField(blank=True, null=True)),
                ('AuthorId', models.BigIntegerField(blank=True, null=True)),
                ('WorkerId', models.BigIntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskReassign',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('TaskId', models.BigIntegerField(blank=True, null=True)),
                ('Appointer', models.TextField(blank=True, null=True)),
                ('Executor', models.TextField(blank=True, null=True)),
                ('Hours', models.FloatField(blank=True, null=True)),
                ('StartDate', models.DateTimeField(blank=True, null=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('IsDone', models.CharField(blank=True, max_length=5, null=True)),
                ('AppointerId', models.BigIntegerField(blank=True, null=True)),
                ('ExecutorId', models.BigIntegerField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TaskReassigns',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('TgId', models.BigIntegerField(blank=True, null=True)),
                ('TgName', models.TextField(blank=True, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('TaskCount', models.IntegerField(blank=True, default=0, null=True)),
                ('Role', models.CharField(blank=True, max_length=20, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
