# Generated by Django 5.2 on 2025-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_task_author_alter_task_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Confirmation',
            field=models.CharField(blank=True, choices=[('Done', 'Done')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='IsReassigned',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='taskreassign',
            name='IsDone',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.CharField(blank=True, choices=[('Consultant', 'Consultant'), ('Developer', 'Developer'), ('Admin', 'Admin')], max_length=50, null=True),
        ),
    ]
